# Author: Khushi Arora
# SAP ID: 500083384
# ROLL NO: R214220616
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: B.TECH CSE, CC&VT

# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "client/client.py" ]